[project]
name = "bettertrack"
version = "0.0.1"
description = "Network tracker in terminal"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.1",
    "ofxtools>=0.9.5",
    "pandas>=2.2.3",
    "yfinance>=0.2.51",
]
